### ISSUE TITLE
func.yaml config: ignored when running locally

### ISSUE THREAD

**Issue by amoAHCP** [fnproject/fdk-java#123]
**given: func.yaml**

version: 0.0.5
runtime: java
cmd: com.example.fn.PojoFunction::greet
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.56
run_image: fnproject/fn-java-fdk:jdk9-1.0.56
memory: 32
format: http
config:
  GREETING: "yes"

**When & What**

When I deploy this function (fn deploy --app java-app --local) it works as expected, but when I execute it (fn build && fn run ) no config attributes are available.
 I checked the map with the configuration, and what I see is:
attributes like "memory" are correctly passed, but no single key/value from config: section. When using UnitTest and passing configuration by using setConfiguration, it works fine

**Comment by rikgibson** [comment]
This issue doesn't belong to this project - this is the Java FDK. `fn run` is no longer supported now either - only `fn deploy` is supported, which per the above description works fine. So closing this.
