### ISSUE TITLE
Add support for creating Java functions using "format:json"

### ISSUE THREAD

**Issue by rikgibson** [fnproject/fdk-java#132]
Hot Java functions can only be created using the HTTP format/container-protocol, which should be deprecated in favour of JSON format. But that can't happen until the Java FDK supports the JSON protocol between Fn Server and the function container...

**Comment by luigisaetta** [comment]
So, as far as I understand, today Java FN are hot by default, even if format is http. 
Documentation is not clear on this point and therefore it seems that with Java you don't have HOT functions.

**Comment by rikgibson** [comment]
@luigisaetta The HTTP protocol format supported by Java functions supports HOT functions.  The JSON protocol format is also a HOT format but isn't supported the Java FDK at this time.  The intention is to add JSON support to the Java FDK, allowing Fn to standardise on the JSON protocol for HOT and to deprecate, and ultimately remove, the HTTP format which isn't supported by some other FDKs.

**Comment by zootalures** [comment]
We're ditching json support in FN in favour of HTTP over unix sockets  closing this.
