### ISSUE TITLE
Readme.md uses "fn run" and "fn call"

### ISSUE THREAD

**Issue by dukescript** [fnproject/fdk-java#187]
The readme.md uses commands that don't exist in v2 like "fn run" or "fn call". This Readme is linked in docs as the tutorial for getting started with the Java FDK, so it's very likely the first thing Java devs try.

**Comment by delabassee** [comment]
Thanks for reporting this. This has been fixed last week (https://github.com/fnproject/fdk-java/pull/186) but not yet merged.
